stages:
  - composer
  - testing
  - deploy

composer:
  stage: composer
  image: composer:1.6
  script:
    - cd app
    - composer install
  cache:
    paths:
      - app/vendor
    key: ${CI_COMMIT_REF_SLUG}
  only:
    - merge_requests
    - master

phpspec:
  stage: testing
  image: php:7.2
  script:
    - pecl install xdebug && docker-php-ext-enable xdebug # Install xdebug for the documentation
    - cd app && php vendor/bin/phpspec run
  artifacts:
    paths:
      - app/coverage
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - app/vendor
    policy: pull
  only:
    - merge_requests
    - master

phpspec2:
  stage: testing
  image: php:7.2
  script:
    - pecl install xdebug && docker-php-ext-enable xdebug # Install xdebug for the documentation
    - cd app && php vendor/bin/phpspec run
  artifacts:
    paths:
      - app/coverage
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - app/vendor
    policy: pull
  only:
    - merge_requests
    - master

deploy:
  stage: deploy
  script:
    - echo "deploy meh!"
  only:
    - master
