stages:
  - composer
  - list

composer:
  stage: composer
  image: composer:1.6
  script:
    - cd app && composer install
  artifacts:
    paths:
      - app/vendor/

list:
  stage: list
  script:
    - ls -lah
