stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building..."
    - mkdir build
    - touch build/hello-world.txt
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Testing..."
    - test -f "build/hello-world.txt"
