version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-fpm
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "app/composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist -d app
      - save_cache:
          key: composer-v1-{{ checksum "app/composer.lock" }}
          paths:
            - app/vendor
      - run: cd app && php vendor/bin/phpspec -c phpspec-ci.yml run
      - store_artifacts:
          path: app/coverage
