version: 2.1

executors:
  make-it-so:
    docker:
      - image: circleci/php:7.2-fpm
    working_directory: /app

jobs:
  build:
    executor: make-it-so
    docker:
      - image: circleci/php:7.2-fpm
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "app/composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist -d app
      - save_cache:
          key: composer-v1-{{ checksum "app/composer.lock" }}
          paths:
            - app/vendor
      - persist_to_workspace:
          root: app
  phpspec:
    executor: make-it-so
    docker:
      - image: circleci/php:7.2-fpm
    steps:
      - attach_workspace:
          - at: app
      - run: cd app && php vendor/bin/phpspec run
      - store_artifacts:
          path: app/coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - phpspec:
          requires:
            - build
