version: 2.1

executors:
  make-it-so:
    docker:
      - image: circleci/php:7.2-fpm
    working_directory: ~/app

jobs:
  build:
    executor: make-it-so
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "app/composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist -d app
      - save_cache:
          key: composer-v1-{{ checksum "app/composer.lock" }}
          paths:
            - app/vendor
      - persist_to_workspace:
          root: ~/app
          paths:
            - app
  phpspec:
    executor: make-it-so
    steps:
      - attach_workspace:
          at: ~/app
      - run: cd app && php vendor/bin/phpspec run
      - store_artifacts:
          path: ~/app/coverage
  phpspec_2:
    executor: make-it-so
    steps:
      - attach_workspace:
          at: ~/app
      - run: cd app && php vendor/bin/phpspec run
      - store_artifacts:
          path: ~/app/coverage

#  deploy:
#    executor: make-it-so
#    steps:
#
#
orbs:
  aws-ecr: circleci/aws-ecr@6.4.0
  aws-ecs: circleci/aws-ecs@0.0.11
  aws-cli: circleci/aws-cli@0.1.16

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - phpspec:
          requires:
            - build
      - phpspec_2:
          requires:
            - build
      - deploy_hold:
          type: approval
          requires:
            - phpspec
            - phpspec_2
      - aws_ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          repo: "ci-demo"
          region: "${AWS_REGION}"
          tag: "${CIRCLE_SHA1}"
      - aws_ecs/update-task-definition:
          requires:
              - aws-ecr/build_and_push_image
          aws-region: ${AWS_REGION}
          family: "ci-task-def"
      - aws_ecs/deploy-service-update:
          requires:
            - aws-ecr/update-task-definition
          aws-region: ${AWS_REGION}
          family: "ci-service"
          cluster-name: "ci-cluster"
          container-image-name-updates: "container=ci-service,tag=${CIRCLE_SHA1}"
