version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "app/composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist -d app
      - save_cache:
          key: composer-v1-{{ checksum "app/composer.lock" }}
          paths:
            - app/vendor
      - run: echo "Hello world!"
