
version: '3'
services:
  nginx:
    container_name: cidemo-nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./:/var/www/html
  php:
    container_name: cidemo-php
    image: php:7.3-fpm
    volumes:
      - ./:/var/www/html
networks:
  default:
    external:
      name: local
